#!/bin/bash
#
# SCRIPT: try4
# AUTHOR: Manas Kashyap
# DATE:   26/03/2020
# REV:    1.1.A (Valid are A, B, D, T and P)
#          (For Alpha, Beta, Dev, Test and Production)
#
#
# PLATFORM: Ubuntu
# 
# PURPOSE: Use "grep" To store nginx log's "get" values in a different output file AND also print the Ip addresses through which the request was thrown.
# REV LIST:
#    DATE        : Date of revision
#    BY          : AUTHOR OF MODIFICATION
#    MODIFICATION: Describe the chages made. What do they enhance.
# 
# set -n   # Uncomment to check script syntax, without execution.
#          # NOTE: Do forget comment it back as it won't allow the 
#          # the script to execute.
#
set +x   # Uncomment this for debugging this shell script.
#
#
################################################################
#          Define Files and Variables here                     #
################################################################

logFilePath="/var/log/nginx/access.log"
#touch nginxlogGrepInfo.txt

################################################################
#          Define Functions here                               #
################################################################

# print_nginx_info(){
# 	grep -i "GET" $logFilePath > nginxlogGrepInfo.txt
# 	cat nginxlogGrepInfo.txt
# }

# displayIPs () {
# 	echo "all the IPs through which the request is thrown are : "
# 	grep -o -E "[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}" nginxlogGrepInfo.txt | sort -u
# }

getIPHits(){
	grep -i "GET" $logFilePath | grep -o -E "[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}" | sort -u
}

################################################################
#          Beginning of Main                                   #
################################################################

# print_nginx_info 
# displayIPs

getIPHits

# End of script
